const KEY_ITEMS = [
  { id: 'Backquote', flags: ['isPrintable'] },
  { id: 'Digit1', flags: ['isPrintable'] },
  { id: 'Digit2', flags: ['isPrintable'] },
  { id: 'Digit3', flags: ['isPrintable'] },
  { id: 'Digit4', flags: ['isPrintable'] },
  { id: 'Digit5', flags: ['isPrintable'] },
  { id: 'Digit6', flags: ['isPrintable'] },
  { id: 'Digit7', flags: ['isPrintable'] },
  { id: 'Digit8', flags: ['isPrintable'] },
  { id: 'Digit9', flags: ['isPrintable'] },
  { id: 'Digit0', flags: ['isPrintable'] },
  { id: 'Minus', flags: ['isPrintable'] },
  { id: 'Equal', flags: ['isPrintable'] },
  { id: 'Backspace', defaultKey: 'Backspace', flags: ['isMaterialIcon', 'isLargeBtn'] },
  { id: 'Tab', defaultKey: 'Tab', flags: [] },
  { id: 'KeyQ', flags: ['isPrintable'] },
  { id: 'KeyW', flags: ['isPrintable'] },
  { id: 'KeyE', flags: ['isPrintable'] },
  { id: 'KeyR', flags: ['isPrintable'] },
  { id: 'KeyT', flags: ['isPrintable'] },
  { id: 'KeyY', flags: ['isPrintable'] },
  { id: 'KeyU', flags: ['isPrintable'] },
  { id: 'KeyI', flags: ['isPrintable'] },
  { id: 'KeyO', flags: ['isPrintable'] },
  { id: 'KeyP', flags: ['isPrintable'] },
  { id: 'BracketLeft', flags: ['isPrintable'] },
  { id: 'BracketRight', flags: ['isPrintable'] },
  { id: 'Backslash', flags: ['isPrintable'] },
  { id: 'Delete', defaultKey: 'Del', flags: [] },
  { id: 'CapsLock', defaultKey: 'CapsLock', flags: ['isMaterialIcon', 'isLargeBtn'] },
  { id: 'KeyA', flags: ['isPrintable'] },
  { id: 'KeyS', flags: ['isPrintable'] },
  { id: 'KeyD', flags: ['isPrintable'] },
  { id: 'KeyF', flags: ['isPrintable'] },
  { id: 'KeyG', flags: ['isPrintable'] },
  { id: 'KeyH', flags: ['isPrintable'] },
  { id: 'KeyJ', flags: ['isPrintable'] },
  { id: 'KeyK', flags: ['isPrintable'] },
  { id: 'KeyL', flags: ['isPrintable'] },
  { id: 'Semicolon', flags: ['isPrintable'] },
  { id: 'Quote', flags: ['isPrintable'] },
  { id: 'Enter', defaultKey: 'Enter', flags: ['isMaterialIcon', 'isLargeBtn'] },
  { id: 'ShiftLeft', defaultKey: 'Shift', flags: ['isLargeBtn'] },
  { id: 'KeyZ', flags: ['isPrintable'] },
  { id: 'KeyX', flags: ['isPrintable'] },
  { id: 'KeyC', flags: ['isPrintable'] },
  { id: 'KeyV', flags: ['isPrintable'] },
  { id: 'KeyB', flags: ['isPrintable'] },
  { id: 'KeyN', flags: ['isPrintable'] },
  { id: 'KeyM', flags: ['isPrintable'] },
  { id: 'Comma', flags: ['isPrintable'] },
  { id: 'Period', flags: ['isPrintable'] },
  { id: 'Slash', flags: ['isPrintable'] },
  { id: 'ArrowUp', flags: ['isMaterialIcon'] },
  { id: 'ShiftRight', defaultKey: 'Shift', flags: ['isLargeBtn'] },
  { id: 'ControlLeft', defaultKey: 'Ctrl', flags: [] },
  { id: 'MetaLeft', defaultKey: 'Win', flags: [] },
  { id: 'AltLeft', defaultKey: 'Alt', flags: [] },
  { id: 'Space', flags: ['isPrintable', 'isLargeBtn'] },
  { id: 'AltRight', defaultKey: 'Alt', flags: [] },
  { id: 'ArrowLeft', flags: ['isMaterialIcon'] },
  { id: 'ArrowDown', flags: ['isMaterialIcon'] },
  { id: 'ArrowRight', flags: ['isMaterialIcon'] },
  { id: 'ControlRight', defaultKey: 'Ctrl', flags: [] },
];

export default KEY_ITEMS;
