const KEY_ITEMS = {
  Backquote: { flags: ['isPrintable'] },
  Digit1: { flags: ['isPrintable'] },
  Digit2: { flags: ['isPrintable'] },
  Digit3: { flags: ['isPrintable'] },
  Digit4: { flags: ['isPrintable'] },
  Digit5: { flags: ['isPrintable'] },
  Digit6: { flags: ['isPrintable'] },
  Digit7: { flags: ['isPrintable'] },
  Digit8: { flags: ['isPrintable'] },
  Digit9: { flags: ['isPrintable'] },
  Digit0: { flags: ['isPrintable'] },
  Minus: { flags: ['isPrintable'] },
  Equal: { flags: ['isPrintable'] },
  Backspace: { defaultKey: 'Backspace', flags: ['isMaterialIcon', 'isLargeBtn'] },
  Tab: { defaultKey: 'Tab', flags: [] },
  KeyQ: { flags: ['isPrintable'] },
  KeyW: { flags: ['isPrintable'] },
  KeyE: { flags: ['isPrintable'] },
  KeyR: { flags: ['isPrintable'] },
  KeyT: { flags: ['isPrintable'] },
  KeyY: { flags: ['isPrintable'] },
  KeyU: { flags: ['isPrintable'] },
  KeyI: { flags: ['isPrintable'] },
  KeyO: { flags: ['isPrintable'] },
  KeyP: { flags: ['isPrintable'] },
  BracketLeft: { flags: ['isPrintable'] },
  BracketRight: { flags: ['isPrintable'] },
  Backslash: { flags: ['isPrintable'] },
  Delete: { defaultKey: 'Del', flags: [] },
  CapsLock: { defaultKey: 'CapsLock', flags: ['isMaterialIcon', 'isLargeBtn'] },
  KeyA: { flags: ['isPrintable'] },
  KeyS: { flags: ['isPrintable'] },
  KeyD: { flags: ['isPrintable'] },
  KeyF: { flags: ['isPrintable'] },
  KeyG: { flags: ['isPrintable'] },
  KeyH: { flags: ['isPrintable'] },
  KeyJ: { flags: ['isPrintable'] },
  KeyK: { flags: ['isPrintable'] },
  KeyL: { flags: ['isPrintable'] },
  Semicolon: { flags: ['isPrintable'] },
  Quote: { flags: ['isPrintable'] },
  Enter: { defaultKey: 'Enter', flags: ['isMaterialIcon', 'isLargeBtn'] },
  ShiftLeft: { defaultKey: 'Shift', flags: ['isLargeBtn'] },
  KeyZ: { flags: ['isPrintable'] },
  KeyX: { flags: ['isPrintable'] },
  KeyC: { flags: ['isPrintable'] },
  KeyV: { flags: ['isPrintable'] },
  KeyB: { flags: ['isPrintable'] },
  KeyN: { flags: ['isPrintable'] },
  KeyM: { flags: ['isPrintable'] },
  Comma: { flags: ['isPrintable'] },
  Period: { flags: ['isPrintable'] },
  Slash: { flags: ['isPrintable'] },
  ArrowUp: { flags: ['isMaterialIcon'] },
  ShiftRight: { defaultKey: 'Shift', flags: ['isLargeBtn'] },
  ControlLeft: { defaultKey: 'Ctrl', flags: [] },
  MetaLeft: { defaultKey: 'Win', flags: [] },
  AltLeft: { defaultKey: 'Alt', flags: [] },
  Space: { flags: ['isPrintable', 'isLargeBtn'] },
  AltRight: { defaultKey: 'Alt', flags: [] },
  ArrowLeft: { flags: ['isMaterialIcon'] },
  ArrowDown: { flags: ['isMaterialIcon'] },
  ArrowRight: { flags: ['isMaterialIcon'] },
  ControlRight: { defaultKey: 'Ctrl', flags: [] },
};

export default KEY_ITEMS;
